twig:
    file_name_pattern: '*.twig'
    form_themes: [
        'bootstrap_5_layout.html.twig',
        'form/enhanced_collection_form_div_layout.html.twig',
        'form/petToys_form.html.twig'
    ]

when@test:
    twig:
        strict_variables: true
